"""add is_enriched to papers, source to user_papers

Revision ID: 43427a22464c
Revises: 6ef68c01634c
Create Date: 2026-10-09 22:37:24.312415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43427a22464c'
down_revision: Union[str, Sequence[str], None] = '6ef68c01634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('is_enriched', sa.Boolean(), nullable=False))
    op.drop_column('papers', 'enriched_by')
    op.add_column('user_papers', sa.Column('source', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_papers', 'source')
    op.add_column('papers', sa.Column('enriched_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('papers', 'is_enriched')
    # ### end Alembic commands ###
