"""add arxiv_url to paper table

Revision ID: 51253c0a933f
Revises: 2ddb430ded9d
Create Date: 2026-09-23 06:03:43.451516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51253c0a933f'
down_revision: Union[str, Sequence[str], None] = '2ddb430ded9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('arxiv_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'arxiv_url')
    # ### end Alembic commands ###
