"""add semantic scholar enrichment fields to papers

Revision ID: 6ef68c01634c
Revises: f42b77c34021
Create Date: 2026-10-06 21:39:54.088888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ef68c01634c'
down_revision: Union[str, Sequence[str], None] = 'f42b77c34021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('influential_citation_count', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('references_count', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('fields_of_study', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('papers', sa.Column('semantic_scholar_id', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('doi', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('enriched_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_papers_semantic_scholar_id'), 'papers', ['semantic_scholar_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_semantic_scholar_id'), table_name='papers')
    op.drop_column('papers', 'enriched_by')
    op.drop_column('papers', 'doi')
    op.drop_column('papers', 'semantic_scholar_id')
    op.drop_column('papers', 'fields_of_study')
    op.drop_column('papers', 'references_count')
    op.drop_column('papers', 'influential_citation_count')
    # ### end Alembic commands ###
