"""create all tables

Revision ID: 7d19b5f98199
Revises: 
Create Date: 2026-09-15 06:09:33.459830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d19b5f98199'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arxiv_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers'))
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_acive', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('digests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('paper_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('synthesis', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='digest_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_digests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digests'))
    )
    op.create_table('paper_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('contributions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('limitations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('recommended_for', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='analysis_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_analyses_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_analyses')),
    sa.UniqueConstraint('paper_id', name=op.f('uq_paper_analyses_paper_id'))
    )
    op.create_table('paper_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_paper_id', sa.UUID(), nullable=False),
    sa.Column('target_paper_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('extends', 'contradicts', 'applies', 'surveys', name='relationship_type'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_paper_id'], ['papers.id'], name=op.f('fk_paper_relationships_source_paper_id_papers')),
    sa.ForeignKeyConstraint(['target_paper_id'], ['papers.id'], name=op.f('fk_paper_relationships_target_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_relationships'))
    )
    op.create_table('user_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('stage_message', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_user_papers_paper_id_papers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_papers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_papers')),
    sa.UniqueConstraint('user_id', 'paper_id', name=op.f('uq_user_papers_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_papers')
    op.drop_table('paper_relationships')
    op.drop_table('paper_analyses')
    op.drop_table('digests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
