"""add external_id and source columns

Revision ID: bf52a219df4a
Revises: 51253c0a933f
Create Date: 2026-09-23 20:35:51.249209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf52a219df4a'
down_revision: Union[str, Sequence[str], None] = '51253c0a933f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('external_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_external_id'), 'papers', ['external_id'], unique=False)
    op.drop_column('papers', 'arxiv_id')
    op.drop_column('papers', 'arxiv_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('arxiv_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('papers', sa.Column('arxiv_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_papers_external_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.drop_column('papers', 'external_url')
    op.drop_column('papers', 'external_id')
    # ### end Alembic commands ###
