"""add external_id and source columns

Revision ID: cb7defbdfb14
Revises: bf52a219df4a
Create Date: 2026-09-23 20:38:04.863896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7defbdfb14'
down_revision: Union[str, Sequence[str], None] = 'bf52a219df4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('source_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_papers_external_id'), table_name='papers')
    op.create_index(op.f('ix_papers_source_id'), 'papers', ['source_id'], unique=False)
    op.create_unique_constraint('uq_paper_source_id_source', 'papers', ['source_id', 'source'])
    op.drop_column('papers', 'external_id')
    op.drop_column('papers', 'external_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('external_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('papers', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_paper_source_id_source', 'papers', type_='unique')
    op.drop_index(op.f('ix_papers_source_id'), table_name='papers')
    op.create_index(op.f('ix_papers_external_id'), 'papers', ['external_id'], unique=False)
    op.drop_column('papers', 'source_url')
    op.drop_column('papers', 'source_id')
    # ### end Alembic commands ###
