"""replace is_enriched with enriched_by on papers

Revision ID: fcc7f370d80f
Revises: 43427a22464c
Create Date: 2026-10-09 22:41:46.980303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc7f370d80f'
down_revision: Union[str, Sequence[str], None] = '43427a22464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('enriched_by', sa.String(), nullable=True))
    op.drop_column('papers', 'is_enriched')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('is_enriched', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('papers', 'enriched_by')
    # ### end Alembic commands ###
